### ISSUE TITLE
I still prefer advancement proposals ;)

### ISSUE THREAD

**Issue by amueller** [scikit-learn/enhancement_proposals#1]

**Comment by GaelVaroquaux** [comment]
To give context: the choice is between 'scikit-learn enhancement proposals' => SLEP and 'scikit-learn advancement proposals' => SLAP.

I am horribly boring, but in the name of being professional and avoiding the possibility of having inappropriate jokes, I would rather avoid using "SLAP".

**Comment by amueller** [comment]
boooring

**Comment by jnothman** [comment]
can the official pronunciation at least be schlepp??

**Comment by GaelVaroquaux** [comment]
> boooring

I am getting old, I guess.
