### ISSUE TITLE
SLEP needed: slicling pipelines

### ISSUE THREAD

**Issue by amueller** [scikit-learn/enhancement_proposals#13]
There's some implementations on slicing and subsetting pipelines but there's no agreement. We need a slep to discuss. https://github.com/scikit-learn/scikit-learn/pull/8431 https://github.com/scikit-learn/scikit-learn/pull/8448 https://github.com/scikit-learn/scikit-learn/issues/8414

**Comment by raamana** [comment]
Just out of curiosity, what would be the utility or applications for this feature be?

**Comment by amueller** [comment]
running the preprocessing pipeline so you know what the input for your model looks like. Or get the feature names for the features that go into the model. I added two related issues.

**Comment by jnothman** [comment]
Applying inverse_transform to the preprocessing pipeline without the last
step is a common application.

But generally, it's something that's relatively easy to do with the current
Pipeline implementation (Pipeline(my_pipeline.steps[:-1])), but with a
proposed Pipeline implementation that clones steps when fitting, this would
be harder

**Comment by adrinjalali** [comment]
Should we close this now that https://github.com/scikit-learn/scikit-learn/pull/2568 is merged?

**Comment by amueller** [comment]
yes.
