### ISSUE TITLE
SLEP007: Meta-estimators section expansion

### ISSUE THREAD

**Issue by adrinjalali** [scikit-learn/enhancement_proposals#31]
@amueller has the following concern on the `meta-estimators` section of the SLEP:

> Shouldn't we list all meta-estimators that are transformers? What about FeatureUnion and RFECV? I guess maybe we're talking about meta-estimators that are not feature selectors, because those are easy.

I'm personally not sure. I kinda prefer to have a guideline which can be used to the meta estimators, rather than listing them in the SLEP.

**Comment by amueller** [comment]
I'm ok with the current phrasing of the SLEP in that regard.
