### ISSUE TITLE
Rename repository to slep for nicer url

### ISSUE THREAD

**Issue by amueller** [scikit-learn/enhancement_proposals#7]
I would suggest renaming this repo to slep so we can have ``scikit-learn.github.io/slep`` instead of ``scikit-learn.github.io/enhancement_proposal``.

**Comment by GaelVaroquaux** [comment]
> I would suggest renaming this repo to slep so we can have scikit-learn.github.io/slep instead of scikit-learn.github.io/enhancement_proposal.

As you wish. I find that "slep" is not a very clear name (though I like
it), and I would find "enhancement_proposal" more explicit.

**Comment by amueller** [comment]
In what context would there be need to clarify? I don't think anyone that remembers either of the urls will be confused.
On the org page each repo has a description, so I think it's pretty clear from the description.
We could probably have the URL not match the repo name but I'm not sure if it's worth the hassle.

**Comment by GaelVaroquaux** [comment]
> In what context would there be need to clarify?

When it is communicated to someone outside the community of scikit-learn developers. But maybe that's not a worthwhile goal.

**Comment by NelleV** [comment]
That's actually an interesting point (although I'm not sure it's worthwile either). It just makes me think of a collaborator giving a presentation, and having to explain "PEP" to a wide audience of non programmers.

Anyhow, I also like the name SLEP, and I really don't have a valuable opinion to share :)

**Comment by amueller** [comment]
> When it is communicated to someone outside the community of scikit-learn developers. 

I don't know what "it" is in this sentence. The url of the website? The github repo?

Not sure where to have the other discussion on the now-closed PR on whether to build in the main website.

**Comment by GaelVaroquaux** [comment]
> I don't know what "it" is in this sentence. The url of the website? The github repo?

The URL of the SLEP.

> Not sure where to have the other discussion on the now-closed PR on whether to build in the main website.

Me neither. But I guess this brings arguments in favor of a separate
tracker, to sort out PRs and issues?

**Comment by GaelVaroquaux** [comment]
>     The URL of the SLEP.

> I think it'll be rare to communicate a SLEP URL to someone outside the project. We will still have a link to enhancement proposals on the main website, right?

Well yes, but think about 'pep8': it's really jargon. That said I don't have a strong opinion. I just like to avoid jargon and acronyms in general.

> Yes. And we kind of had that discussion on the governance doc. I think we should just put some sphinx in here and be done with it for now maybe?

+1

**Comment by jnothman** [comment]
I'm not in the mood for thinking about these things, sorry. Happy with
whatever goes.

**Comment by agramfort** [comment]
I think enhancement_proposals is more explicit.

**Comment by amueller** [comment]
alright then

**Comment by chkoar** [comment]
Late to the game but I would rename the repo as the rtd site. `scikit-learn-enhancement-proposals` or at least `enhancement-proposals`.
