### ISSUE TITLE
Update of SLEP002

### ISSUE THREAD

**Issue by julien-blanchon** [scikit-learn/enhancement_proposals#70]
Any update and news for [SLEP002](https://scikit-learn-enhancement-proposals.readthedocs.io/en/latest/slep002/proposal.html#id5)

**Comment by amueller** [comment]
I don't think anyone is working on that right now. Do you have a specific use-case in mind or something you'd like to achieve?

**Comment by lorentzenchr** [comment]
No actionable issue and inactive.
